Add files via upload

diff --git a/conexao b/conexao
--- a/conexao
+++ b/conexao
@@ -1,12 +1,14 @@
 #!/bin/bash
 #====================================================
-#	SCRIPT: CONEXAO SSHPLUS MANAGER
-#	DESENVOLVIDO POR:	CRAZY_VPN
-#	DATA ATUALIZACAO:	16-03-2021 
-#	CONTATO TELEGRAM:	http://t.me/crazy_vpn
-#	CANAL TELEGRAM:	http://t.me/sshplus
+#	@kiritosshxd
 #====================================================
-[[ $(awk -F" " '{print $2}' /usr/lib/licence) == "@CRAZY_VPN" ]] && {
+cor1='\033[41;1;37m'
+cor2='\033[44;1;37m'
+scor='\033[0m'
+GREEN='\033[1;32m'
+YELLOW='\033[1;33m'
+SCOLOR='\033[0m'
+[[ $(awk -F" " '{print $2}' /usr/lib/licence) == "@KIRITO_SSH" ]] && {
 	ram1=$(free -h | grep -i mem | awk {'print $2'})
 	ram2=$(free -h | grep -i mem | awk {'print $4'})
 	ram3=$(free -h | grep -i mem | awk {'print $3'})
@@ -460,7 +462,153 @@
 			}
 		fi
 	}
+    	fun_chisel() {
+		clear
+		echo -e "\E[44;1;37m            GERENCIAR CHISEL             \E[0m"
+		echo ""
 
+
+		[[ "$(netstat -tlpn | grep 'docker' | wc -l)" != '0' ]] && {
+			sks='\033[1;32mON'
+			echo -e "\033[1;33mPORTAS\033[1;37m: \033[1;32m$(netstat -nplt | grep 'docker' | awk {'print $4'} | cut -d: -f2 | xargs)"
+		} || {
+			sks='\033[1;31mOFF'
+		}
+        [[ "$(netstat -tlpn | grep 'docker' | wc -l)" != '0' ]] && {
+				chiselsts="\033[1;32m◉ "
+			} || {
+				chiselsts="\033[1;31m○ "
+			}
+		echo ""
+		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mATIVAR CHISEL $chiselsts \033[0m"
+		echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREINICIAR CHISEL\033[0m"
+		echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
+		echo ""
+		echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
+		read resposta
+		if [[ "$resposta" = '1' ]]; then
+			if netstat -nltp | grep 'docker' 1>/dev/null 2>/dev/null; then
+				clear
+				echo -e "\E[41;1;37m             CHISEL              \E[0m"
+				echo ""
+				fun_chiseloff() {
+					docker stop chisel
+                    docker rm chisel
+					docker.io stop chisel
+                    docker.io rm chisel
+
+				}
+				echo -e "\033[1;32mDESATIVANDO CHISEL\033[1;33m"
+				echo ""
+				fun_bar 'fun_chiseloff'
+				echo ""
+				echo -e "\033[1;32mCHISEL DESATIVADO COM SUCESSO!\033[1;33m"
+				sleep 3
+				fun_chisel
+			else
+                clear
+                fun_installdocker() {
+                    _pacotes=("docker" "docker.io")
+                    for _prog in ${_pacotes[@]}; do
+                    apt install $_prog -y
+                    done
+                }
+                echo -e "\n${YELLOW}ESTEJA CIENTE QUE ESSE METODO É INSTAVEL\nPODE OU NÃO FUNCIONAR NA SUA MAQUINA\nFIQUE CIENTE DOS RISCOS ! ${SCOLOR}\n"
+                echo -ne "${GREEN}DESEJA CONTINUAR A INSTALACAO ? ${YELLOW}[s/n]:${SCOLOR} "
+                read resp
+                [[ "$resp" != @(s|sim|S|SIM) ]] && {
+                    echo -e "\n${RED}Retornando...${SCOLOR}"
+                    sleep 2
+                    conexao
+                }
+                echo -e "\n\033[1;32mSuportado Ubuntu 16+\033[1;33m"
+                echo -e "\n\033[1;32mINSTALANDO O CHISEL !\033[1;33m"
+				echo ""
+				fun_bar 'fun_installdocker'
+				clear
+				echo -e "\E[44;1;37m             CHISEL              \E[0m"
+				echo ""
+				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m: "
+				read porta
+				[[ -z "$porta" ]] && {
+					echo ""
+					echo -e "\033[1;31mPorta invalida!"
+					sleep 3
+					clear
+					fun_chisel
+				}
+				verif_ptrs $porta
+                clear
+                echo -ne "\033[1;32mNome do usuário:\033[1;37m ";read username
+                [[ -z $username ]] && {
+                    echo -e "\n${cor1}Nome de usuário vazio ou invalido!${scor}\n"
+                    fun_chisel
+                }
+                [[ ${username} != ?(+|-)+([a-zA-Z0-9]) ]] && {
+                    echo -e "\n${cor1}Você digitou um nome de usuário inválido!${scor}"
+                    echo -e "${cor1}Não use espaços, acentos ou caracteres especiais!${scor}\n"
+                    fun_chisel
+                }
+                sizemin=$(echo ${#username})
+                [[ $sizemin -lt 2 ]] && {
+                    echo -e "\n${cor1}Você digitou um nome de usuário muito curto${scor}"
+                    echo -e "${cor1}use no mínimo dois caracteres!${scor}\n"
+                    fun_chisel
+                }
+                sizemax=$(echo ${#username})
+                [[ $sizemax -gt 10 ]] && {
+                    echo -e "\n${cor1}Você digitou um nome de usuário muito grande"
+                    echo -e "${cor1}use no máximo 10 caracteres!${scor}\n"
+                    fun_chisel
+                }
+                echo -ne "\033[1;32mSenha:\033[1;37m ";read password
+                [[ -z $password ]] && {
+                    echo -e "\n${cor1}Senha vazia ou invalida!${scor}\n"
+                    fun_chisel 
+                }
+                sizepass=$(echo ${#password})
+                [[ $sizepass -lt 4 ]] && {
+                    echo -e "\n${cor1}Senha curta!, use no mínimo 4 caracteres${scor}\n"
+                    fun_chisel        
+                }
+                echo -e "\n\033[1;32mCONFIGURANDO CHISEL !\033[0m"
+				echo ""
+                fun_inichisel() {
+                    docker run --name chisel -p $porta:$porta -d --restart always jpillora/chisel server -p $porta --socks5 --key supersecret --auth "$username:$password"
+                    docker.io run --name chisel -p $porta:$porta -d --restart always jpillora/chisel server -p $porta --socks5 --key supersecret --auth "$username:$password"
+                }
+                fun_bar 'fun_inichisel'
+                clear
+                echo -e "\n\033[1;32mCHISEL INSTALADO COM SUCESSO !\033[1;31m PORTA: \033[1;33m${porta}\033[0m"
+				sleep 3
+				clear
+				fun_chisel
+            fi
+        elif [[ "$resposta" = '2' ]]; then
+            clear
+            echo -e "\n\033[1;32mREINICIANDO CHISEL !\033[1;33m"
+			echo ""
+            fun_attchisel() {
+                docker restart chisel
+                docker.io restart chisel
+            }
+            fun_attchisel
+            clear
+            echo -e "\n\033[1;32mCHISEL REINICIANDO COM SUCESSO !\033[1;33m"
+            sleep 1
+            fun_chisel
+        elif [[ "$resposta" = '0' ]]; then
+			echo ""
+			echo -e "\033[1;31mRetornando...\033[0m"
+			sleep 1
+			fun_conexao
+		else
+			echo ""
+			echo -e "\033[1;31mOpcao invalida !\033[0m"
+			sleep 1
+			fun_socks
+		fi
+    }
 	inst_ssl() {
 		if netstat -nltp | grep 'stunnel4' 1>/dev/null 2>/dev/null; then
 			[[ $(netstat -nltp | grep 'stunnel4' | wc -l) != '0' ]] && sslt=$(netstat -nplt | grep stunnel4 | awk {'print $4'} | awk -F ":" {'print $2'} | xargs) || sslt="\033[1;31mINDISPONIVEL"
@@ -524,6 +672,30 @@
 			}
 		else
 			clear
+			echo -e "\E[44;1;37m              INSTALAR SSL TUNNEL               \E[0m"
+			echo ""
+			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mINSTALAR SSL TUNNEL PADRÃO\033[0m"
+			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mINSTALAR SSL TUNNEL WEBSOCKET\033[0m"
+			echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
+			echo ""
+			echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
+			read resposta
+			echo ""
+            if [[ "$resposta" = '1' ]]; then
+                portssl='22'
+            elif [[ "$resposta" = '2' ]]; then     
+                portssl='80'
+            elif [[ "$resposta" = '0' ]]; then
+				echo -e "\033[1;31mRetornando...\033[0m"
+				sleep 3
+				fun_conexao
+            else
+			echo ""
+			echo -e "\033[1;31mOpcao invalida !\033[0m"
+			sleep 1
+			inst_ssl
+		fi
+            clear
 			echo -e "\E[44;1;37m           INSTALADOR SSL TUNNEL             \E[0m"
 			echo -e "\n\033[1;33mVC ESTA PRESTES A INSTALAR O SSL TUNNEL !\033[0m"
 			echo ""
@@ -532,7 +704,8 @@
 			[[ "$resposta" = 's' ]] && {
 				echo -e "\n\033[1;33mDEFINA UMA PORTA PARA O SSL TUNNEL !\033[0m"
 				echo ""
-				read -p "$(echo -e "\033[1;32mQUAL PORTA DESEJA UTILIZAR? \033[1;37m")" -e -i 3128 porta
+				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m "
+                read porta
 				[[ -z "$porta" ]] && {
 					echo ""
 					echo -e "\033[1;31mPorta invalida!"
@@ -547,7 +720,7 @@
 				echo -e "\n\033[1;32mCONFIGURANDO O SSL TUNNEL !\033[0m"
 				echo ""
 				ssl_conf() {
-					echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 127.0.0.1:22\naccept = ${porta}" >/etc/stunnel/stunnel.conf
+					echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 127.0.0.1:$portssl\naccept = ${porta}" >/etc/stunnel/stunnel.conf
 				}
 				fun_bar 'ssl_conf'
 				echo -e "\n\033[1;32mCRIANDO CERTIFICADO !\033[0m"
@@ -567,7 +740,7 @@
 					#cat cert.pem key.pem >>/etc/stunnel/stunnel.pem
 					#rm key.pem cert.pem >/dev/null 2>&1
 					sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
-					cd /etc/stunnel && wget https://raw.githubusercontent.com/RPVIP/sshplus/main/Sistema/script/stunnel.pem && cd $HOME
+					cd /etc/stunnel && wget https://raw.githubusercontent.com/rodrigo12xd/SSHPLUS/master/stunnel.pem && cd $HOME
 				}
 				fun_bar 'ssl_certif'
 				echo -e "\n\033[1;32mINICIANDO O SSL TUNNEL !\033[0m"
@@ -1071,7 +1244,7 @@
 			# Adquirindo easy-rsa
 			echo ""
 			fun_dep() {
-				wget -O ~/EasyRSA-3.0.1.tgz "https://github.com/RPVIP/sshplus/raw/master/Install/EasyRSA-3.0.1.tgz"
+				wget -O ~/EasyRSA-3.0.1.tgz "https://github.com/rodrigo12xd/SSHPLUS/raw/master/Install/EasyRSA-3.0.1.tgz"
 				[[ ! -e $HOME/EasyRSA-3.0.1.tgz ]] && {
 					wget -O ~/EasyRSA-3.0.1.tgz "http://sshplus.xyz/script/EasyRSA-3.0.1.tgz"
 				}
@@ -1277,7 +1450,7 @@ exit 0' >$RCLOCAL
 		echo ""
 		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mSOCKS SSH $var_sks1 \033[0m"
 		echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mWEBSOCKET $var_sks2 \033[0m"
-		echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mSOCKS OEPNVPN $sksop \033[0m"
+		echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mSOCKS OPENVPN $sksop \033[0m"
 		echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mABRIR PORTA\033[0m"
 		echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mALTERAR STATUS SOCKS SSH\033[0m"
         echo -e "\033[1;31m[\033[1;36m6\033[1;31m] \033[1;37m• \033[1;33mALTERAR STATUS WEBSOCKET\033[0m"
@@ -1524,7 +1697,7 @@ exit 0' >$RCLOCAL
 				echo -e "\033[1;31m[\033[1;36m10\033[1;31m]\033[1;33m SEM COR"
 				echo ""
 				echo -ne "\033[1;32mQUAL A COR\033[1;31m ?\033[1;37m : "
-				read cor_sts
+				read sts_cor
 				if [[ "$sts_cor" = "1" ]] || [[ "$sts_cor" = "01" ]]; then
 					cor_sts='blue'
 				elif [[ "$sts_cor" = "2" ]] || [[ "$sts_cor" = "02" ]]; then
@@ -1555,7 +1728,6 @@ exit 0' >$RCLOCAL
 					sleep 1
 					cor_old=$(grep 'color=' /etc/SSHPlus/proxy.py | cut -d '"' -f2)
 					sed -i "s/\b$cor_old\b/$cor_sts/g" /etc/SSHPlus/proxy.py
-
 				}
 				echo ""
 				echo -e "\033[1;32mALTERANDO STATUS!"
@@ -1573,7 +1745,7 @@ exit 0' >$RCLOCAL
 						screen -dmS proxy python /etc/SSHPlus/proxy.py $_Ptsks
 						rm /tmp/Pt_sks
 					fi
-				}
+                }
 				echo ""
 				echo -e "\033[1;32mREINICIANDO PROXY SOCKS!"
 				echo ""
@@ -1825,11 +1997,17 @@ exit 0' >$RCLOCAL
 			clear
 			echo -e "\E[44;1;37m                MODO DE CONEXAO                 \E[0m\n"
 			echo -e "\033[1;32mSERVICO: \033[1;33mOPENSSH \033[1;32mPORTA: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)" && sts6="\033[1;32m◉ "
-			[[ "$(ps x | grep 'slow_dns' | grep -v 'grep'|wc -l)" != '0' ]] && {
+			[[ "$(netstat -tlpn | grep 'docker' | wc -l)" != '0' ]] && {
+				echo -e "\033[1;32mSERVICO: \033[1;33mCHISEL: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'docker' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sts8="\033[1;32m◉ "
 			} || {
 				sts8="\033[1;31m○ "
 			}
+			[[ "$(ps x | grep 'slow_dns' | grep -v 'grep'|wc -l)" != '0' ]] && {
+				sts9="\033[1;32m◉ "
+			} || {
+				sts9="\033[1;31m○ "
+			}            
 			[[ "$(netstat -tlpn | grep 'sslh' | wc -l)" != '0' ]] && {
 				echo -e "\033[1;32mSERVICO: \033[1;33mSSLH: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'sslh' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sts7="\033[1;32m◉ "
@@ -1877,8 +2055,9 @@ exit 0' >$RCLOCAL
 [\033[1;36m05\033[1;31m] \033[1;37m• \033[1;33mPROXY SOCKS $sts4\033[1;31m
 [\033[1;36m06\033[1;31m] \033[1;37m• \033[1;33mSSL TUNNEL $sts3\033[1;31m
 [\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mSSLH MULTIPLEX $sts7\033[1;31m
-[\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mSLOWDNS $sts8\033[1;31m
-[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mVOLTAR \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m
+[\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mCHISEL $sts8\033[1;31m
+[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mSLOWDNS $sts9\033[1;31m
+[\033[1;36m10\033[1;31m] \033[1;37m• \033[1;33mVOLTAR \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m
 [\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mSAIR \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
 			echo ""
 			echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
@@ -1911,9 +2090,12 @@ exit 0' >$RCLOCAL
 				fun_sslh
 				;;
 		    8 | 08)
+				fun_chisel
+                ;;              
+		    9 | 09)
 				slow_dns
 				;;
-			9 | 09)
+			10 | 10)
 				menu
 				;;
 			0 | 00)
